from __future__ import annotations

from matplotlib.backends.backend_qtagg import FigureCanvasQTAgg, NavigationToolbar2QT
from matplotlib.figure import Figure
from PySide6.QtCore import Qt
from PySide6.QtWidgets import (
    QApplication,
    QAbstractItemView,
    QComboBox,
    QGridLayout,
    QGroupBox,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QListWidget,
    QPushButton,
    QRadioButton,
    QScrollArea,
    QSpinBox,
    QSplitter,
    QTextEdit,
    QVBoxLayout,
    QWidget,
)


def section(title):
    box = QGroupBox(title)
    box.setLayout(QVBoxLayout())
    box.layout().setContentsMargins(8, 8, 8, 8)
    box.layout().setSpacing(6)
    return box


def compact_button(label, max_width=124, min_height=24):
    button = QPushButton(label)
    button.setMaximumWidth(max_width)
    button.setMinimumHeight(min_height)
    button.setMaximumHeight(min_height + 4)
    return button


def build_ui(window, instrument, max_points, list_widget_cls: type[QListWidget]):
    root = QWidget()
    root_layout = QHBoxLayout(root)
    root_layout.setContentsMargins(10, 10, 10, 10)

    splitter = QSplitter(Qt.Horizontal)
    window.main_splitter = splitter
    root_layout.addWidget(splitter)
    window.setCentralWidget(root)

    left = QWidget()
    left_layout = QVBoxLayout(left)
    left_layout.setContentsMargins(0, 0, 0, 0)
    left_layout.setSpacing(6)

    data_box = section("Data")
    data_grid = QGridLayout()
    data_box.layout().addLayout(data_grid)
    data_grid.addWidget(QLabel("Folder"), 0, 0, 1, 3)
    window.folder_edit = QLineEdit(window.base_dir)
    window.folder_edit.setToolTip("Folder containing the FCS files for the current run.")
    data_grid.addWidget(window.folder_edit, 1, 0, 1, 3)
    window.browse_button = compact_button("Browse", 96)
    window.browse_button.setToolTip("Browse to a folder of FCS files.")
    window.browse_button.clicked.connect(window._browse_folder)
    data_grid.addWidget(window.browse_button, 2, 0)
    window.instrument_combo = QComboBox()
    window.instrument_combo.addItems(["Cytoflex", "Symphony"])
    window.instrument_combo.setCurrentText(instrument)
    data_grid.addWidget(window.instrument_combo, 2, 1)
    window.load_button = compact_button("Load", 96)
    window.load_button.setToolTip("Scan the selected folder, detect wells, and load channel metadata.")
    window.load_button.clicked.connect(window.load_folder)
    data_grid.addWidget(window.load_button, 2, 2)
    window.compensation_button = compact_button("Comp", 96)
    window.compensation_button.setToolTip("Open the compensation editor to enable or edit a spillover matrix.")
    window.compensation_button.clicked.connect(window.open_compensation_editor)
    data_grid.addWidget(window.compensation_button, 3, 0)
    window.compensation_status_label = QLabel("Compensation: off")
    window.compensation_status_label.setWordWrap(True)
    data_grid.addWidget(window.compensation_status_label, 3, 1, 1, 2)
    data_grid.addWidget(QLabel("Wells"), 4, 0, 1, 3)
    window.well_list = list_widget_cls()
    window.well_list.setToolTip("Select one or more wells to plot and analyze together.")
    window.well_list.setSelectionMode(QAbstractItemView.ExtendedSelection)
    window.well_list.itemSelectionChanged.connect(window._on_well_selection_changed)
    window.well_list.setMaximumHeight(180)
    data_grid.addWidget(window.well_list, 5, 0, 1, 3)
    data_grid.addWidget(QLabel("Selected Sample"), 6, 0)
    window.sample_name_edit = QLineEdit("")
    data_grid.addWidget(window.sample_name_edit, 7, 0, 1, 3)
    window.assign_sample_button = compact_button("Apply", 100)
    window.assign_sample_button.clicked.connect(window._assign_sample_name_to_selected_wells)
    data_grid.addWidget(window.assign_sample_button, 8, 0)
    window.exclude_toggle_button = compact_button("Exclude", 100)
    window.exclude_toggle_button.clicked.connect(window._toggle_exclude_selected_wells)
    data_grid.addWidget(window.exclude_toggle_button, 8, 1)
    window.clear_metadata_button = compact_button("Clear", 100)
    window.clear_metadata_button.clicked.connect(window._clear_selected_metadata)
    data_grid.addWidget(window.clear_metadata_button, 8, 2)
    window.plate_editor_button = compact_button("Plate Map", 106)
    window.plate_editor_button.clicked.connect(window.open_plate_map_editor)
    data_grid.addWidget(window.plate_editor_button, 9, 0)
    window.save_session_button = compact_button("Save", 96)
    window.save_session_button.clicked.connect(window.save_session)
    data_grid.addWidget(window.save_session_button, 9, 1)
    window.load_session_button = compact_button("Open", 96)
    window.load_session_button.clicked.connect(window.load_session)
    data_grid.addWidget(window.load_session_button, 9, 2)
    window.recent_session_combo = QComboBox()
    data_grid.addWidget(window.recent_session_combo, 10, 0, 1, 2)
    window.open_recent_button = compact_button("Recent", 96)
    window.open_recent_button.clicked.connect(window.load_recent_session)
    data_grid.addWidget(window.open_recent_button, 10, 2)
    window.check_updates_button = compact_button("Updates", 96)
    window.check_updates_button.clicked.connect(window.check_for_updates)
    data_grid.addWidget(window.check_updates_button, 11, 0)
    window.version_label = QLabel(f"Version {window._app_version_text()}")
    data_grid.addWidget(window.version_label, 11, 1, 1, 2)
    left_layout.addWidget(data_box)

    plot_box = section("Plot")
    plot_grid = QGridLayout()
    plot_box.layout().addLayout(plot_grid)
    plot_grid.addWidget(QLabel("Population"), 0, 0)
    window.population_combo = QComboBox()
    window.population_combo.addItems(["All Events"])
    window.population_combo.setToolTip("Choose which saved population to display as the parent view.")
    window.population_combo.currentIndexChanged.connect(window._on_population_changed)
    plot_grid.addWidget(window.population_combo, 1, 0)
    plot_grid.addWidget(QLabel("Max Points"), 0, 1)
    window.max_points_spin = QSpinBox()
    window.max_points_spin.setRange(1000, 50000)
    window.max_points_spin.setSingleStep(1000)
    window.max_points_spin.setValue(int(max_points))
    window.max_points_spin.valueChanged.connect(window._trigger_auto_plot)
    plot_grid.addWidget(window.max_points_spin, 1, 1)
    window.plot_button = compact_button("Plot", 96)
    window.plot_button.setToolTip("Render the current wells, population, channels, and transforms.")
    window.plot_button.clicked.connect(window.plot_population)
    plot_grid.addWidget(window.plot_button, 1, 2)
    window.zoom_box_button = compact_button("Zoom Box", 104)
    window.zoom_box_button.setToolTip("Drag a box on the plot to set padded axis limits around that region.")
    window.zoom_box_button.clicked.connect(window.start_zoom_box)
    plot_grid.addWidget(window.zoom_box_button, 1, 3)
    window.reset_zoom_button = compact_button("Reset", 96)
    window.reset_zoom_button.setToolTip("Clear manual zoom overrides for the current plot axes.")
    window.reset_zoom_button.clicked.connect(window.reset_zoom)
    plot_grid.addWidget(window.reset_zoom_button, 1, 4)
    window.graph_options_button = compact_button("Options", 104)
    window.graph_options_button.setToolTip("Set manual graph limits and slider-based axis overrides.")
    window.graph_options_button.clicked.connect(window.open_graph_options_dialog)
    plot_grid.addWidget(window.graph_options_button, 2, 4)

    plot_grid.addWidget(QLabel("X Axis"), 3, 0)
    window.x_combo = QComboBox()
    window.x_combo.currentIndexChanged.connect(window._on_channel_changed)
    plot_grid.addWidget(window.x_combo, 4, 0)
    plot_grid.addWidget(QLabel("Y Axis"), 3, 1)
    window.y_combo = QComboBox()
    window.y_combo.currentIndexChanged.connect(window._on_channel_changed)
    plot_grid.addWidget(window.y_combo, 4, 1)
    plot_grid.addWidget(QLabel("Plot Mode"), 3, 2)
    window.plot_mode_combo = QComboBox()
    window.plot_mode_combo.addItems(["scatter", "hex density", "count histogram"])
    window.plot_mode_combo.setToolTip("Switch between point scatter, density hexbin, and histogram views.")
    window.plot_mode_combo.currentIndexChanged.connect(window._on_channel_changed)
    plot_grid.addWidget(window.plot_mode_combo, 4, 2)
    window.hex_size_label = QLabel("Hex Size")
    plot_grid.addWidget(window.hex_size_label, 3, 3)
    window.hex_size_spin = QSpinBox()
    window.hex_size_spin.setRange(5, 120)
    window.hex_size_spin.setSingleStep(1)
    window.hex_size_spin.setValue(10)
    window.hex_size_spin.setToolTip("Set the hexbin grid size for hex density plots.")
    window.hex_size_spin.valueChanged.connect(window._trigger_auto_plot)
    plot_grid.addWidget(window.hex_size_spin, 4, 3)

    plot_grid.addWidget(QLabel("X Transform"), 5, 0)
    window.x_transform_combo = QComboBox()
    window.x_transform_combo.addItems(["linear", "log10", "arcsinh"])
    window.x_transform_combo.setCurrentText("arcsinh")
    window.x_transform_combo.currentIndexChanged.connect(window._trigger_auto_plot)
    plot_grid.addWidget(window.x_transform_combo, 6, 0)
    plot_grid.addWidget(QLabel("X Cofactor"), 5, 1)
    window.x_cofactor_spin = QSpinBox()
    window.x_cofactor_spin.setRange(1, 10000)
    window.x_cofactor_spin.setValue(150)
    window.x_cofactor_spin.valueChanged.connect(window._trigger_auto_plot)
    plot_grid.addWidget(window.x_cofactor_spin, 6, 1)
    plot_grid.addWidget(QLabel("Y Transform"), 5, 2)
    window.y_transform_combo = QComboBox()
    window.y_transform_combo.addItems(["linear", "log10", "arcsinh"])
    window.y_transform_combo.setCurrentText("arcsinh")
    window.y_transform_combo.currentIndexChanged.connect(window._trigger_auto_plot)
    plot_grid.addWidget(window.y_transform_combo, 6, 2)
    plot_grid.addWidget(QLabel("Y Cofactor"), 5, 3)
    window.y_cofactor_spin = QSpinBox()
    window.y_cofactor_spin.setRange(1, 10000)
    window.y_cofactor_spin.setValue(150)
    window.y_cofactor_spin.valueChanged.connect(window._trigger_auto_plot)
    plot_grid.addWidget(window.y_cofactor_spin, 6, 3)

    window.qt_plot_note = QLabel("Qt port currently supports folder load, well selection, plotting, and basic gate drawing.")
    window.qt_plot_note.setWordWrap(True)
    plot_box.layout().addWidget(window.qt_plot_note)
    auto_row = QHBoxLayout()
    auto_row.addWidget(QLabel("Auto Update"))
    window.auto_plot_auto_radio = QRadioButton("Auto")
    window.auto_plot_manual_radio = QRadioButton("Manual")
    window.auto_plot_auto_radio.setChecked(True)
    window.auto_plot_auto_radio.toggled.connect(window._on_auto_plot_mode_changed)
    auto_row.addWidget(window.auto_plot_auto_radio)
    auto_row.addWidget(window.auto_plot_manual_radio)
    auto_row.addStretch(1)
    plot_box.layout().addLayout(auto_row)
    left_layout.addWidget(plot_box)

    gating_box = section("Gating")
    gating_grid = QGridLayout()
    gating_box.layout().addLayout(gating_grid)
    gating_grid.addWidget(QLabel("Gate Type"), 0, 0)
    window.gate_type_combo = QComboBox()
    window.gate_type_combo.addItems(["polygon", "rectangle", "quad", "vertical", "horizontal"])
    window.gate_type_combo.setToolTip("Choose the gate shape to draw on the current plot.")
    window.gate_type_combo.currentIndexChanged.connect(window._on_gate_type_changed)
    gating_grid.addWidget(window.gate_type_combo, 1, 0)
    gating_grid.addWidget(QLabel("Gate Name"), 0, 1)
    window.gate_name_edit = QLineEdit("gate_1")
    gating_grid.addWidget(window.gate_name_edit, 1, 1, 1, 2)
    window.start_draw_button = compact_button("Draw", 96)
    window.start_draw_button.setToolTip("Start drawing the selected gate type on the plot.")
    window.start_draw_button.clicked.connect(window.start_drawing)
    gating_grid.addWidget(window.start_draw_button, 2, 0)
    window.clear_pending_button = compact_button("Clear", 96)
    window.clear_pending_button.setToolTip("Clear the pending gate preview without saving it.")
    window.clear_pending_button.clicked.connect(window.clear_pending)
    gating_grid.addWidget(window.clear_pending_button, 2, 1)
    window.save_gate_button = compact_button("Save", 96)
    window.save_gate_button.setToolTip("Save the pending gate into the current session.")
    window.save_gate_button.clicked.connect(window.save_gate)
    gating_grid.addWidget(window.save_gate_button, 2, 2)
    window.move_gate_button = compact_button("Move", 96)
    window.move_gate_button.setToolTip("Optional explicit move mode. Direct dragging on a selected gate is also enabled.")
    window.move_gate_button.clicked.connect(window.start_move_selected_gate)
    gating_grid.addWidget(window.move_gate_button, 3, 0)
    window.delete_gate_button = compact_button("Delete", 96)
    window.delete_gate_button.clicked.connect(window.delete_selected_gate)
    gating_grid.addWidget(window.delete_gate_button, 3, 1)
    window.rename_gate_button = compact_button("Rename", 96)
    window.rename_gate_button.clicked.connect(window.rename_selected_gate)
    gating_grid.addWidget(window.rename_gate_button, 3, 2)
    window.recolor_gate_button = compact_button("Color", 96)
    window.recolor_gate_button.clicked.connect(window.recolor_selected_gate)
    gating_grid.addWidget(window.recolor_gate_button, 4, 0)
    window.copy_gate_names_button = compact_button("Copy", 96)
    window.copy_gate_names_button.clicked.connect(window.copy_gate_names)
    gating_grid.addWidget(window.copy_gate_names_button, 4, 1)
    window.save_template_button = compact_button("Save Template", 124)
    window.save_template_button.clicked.connect(window.save_gate_template)
    gating_grid.addWidget(window.save_template_button, 4, 2)
    window.load_template_button = compact_button("Load Template", 124)
    window.load_template_button.clicked.connect(window.load_gate_template)
    gating_grid.addWidget(window.load_template_button, 5, 0, 1, 3)
    window.mode_label = QLabel("Mode: idle")
    gating_box.layout().addWidget(window.mode_label)
    gating_box.layout().addWidget(QLabel("Saved Gates"))
    window.saved_gate_list = QListWidget()
    window.saved_gate_list.setToolTip("Saved gates are listed with full hierarchy paths. Select one to edit or inspect it.")
    window.saved_gate_list.itemSelectionChanged.connect(window._on_saved_gate_selected)
    window.saved_gate_list.setMaximumHeight(120)
    gating_box.layout().addWidget(window.saved_gate_list)
    window.gate_summary = QTextEdit()
    window.gate_summary.setReadOnly(True)
    window.gate_summary.setPlainText("Select a gate to view summary.")
    window.gate_summary.setMaximumHeight(92)
    gating_box.layout().addWidget(window.gate_summary)
    export_row = QHBoxLayout()
    window.export_summary_button = compact_button("Summary", 100)
    window.export_summary_button.clicked.connect(window.export_gate_summary_csv)
    export_row.addWidget(window.export_summary_button)
    window.export_intensity_button = compact_button("Intensity", 100)
    window.export_intensity_button.clicked.connect(window.export_intensity_csv)
    export_row.addWidget(window.export_intensity_button)
    window.export_plate_button = compact_button("Plate", 92)
    window.export_plate_button.clicked.connect(window.export_plate_metadata_csv)
    export_row.addWidget(window.export_plate_button)
    gating_box.layout().addLayout(export_row)
    analysis_row = QHBoxLayout()
    window.analysis_preview_button = compact_button("Preview", 92)
    window.analysis_preview_button.clicked.connect(window.open_analysis_preview)
    analysis_row.addWidget(window.analysis_preview_button)
    window.export_html_button = compact_button("HTML", 80)
    window.export_html_button.clicked.connect(window.export_html_report)
    analysis_row.addWidget(window.export_html_button)
    window.export_notebook_button = compact_button("Notebook", 92)
    window.export_notebook_button.clicked.connect(window.create_analysis_notebook)
    analysis_row.addWidget(window.export_notebook_button)
    gating_box.layout().addLayout(analysis_row)
    left_layout.addWidget(gating_box)

    status_box = section("Status")
    status_layout = status_box.layout()
    window.status_label = QLabel("Choose a folder and click Load Folder.")
    window.status_label.setWordWrap(True)
    status_layout.addWidget(window.status_label)
    window.channel_status_label = QLabel("Channel union and mixed-channel warnings will appear here.")
    window.channel_status_label.setWordWrap(True)
    status_layout.addWidget(window.channel_status_label)
    left_layout.addWidget(status_box)
    left_layout.addStretch(1)

    right = QWidget()
    right_layout = QVBoxLayout(right)
    right_layout.setContentsMargins(0, 0, 0, 0)
    right_layout.setSpacing(10)
    right_splitter = QSplitter(Qt.Vertical)
    window.right_splitter = right_splitter
    right_layout.addWidget(right_splitter)

    plot_panel = QGroupBox("Interactive Plot")
    plot_panel.setLayout(QVBoxLayout())
    window.figure = Figure(figsize=(8, 7), dpi=100)
    window.ax = window.figure.add_subplot(111)
    window.ax.set_title("No population plotted")
    window.ax.set_xlabel("X")
    window.ax.set_ylabel("Y")
    window.canvas = FigureCanvasQTAgg(window.figure)
    window.canvas.setMinimumSize(520, 520)
    window.canvas.setFocusPolicy(Qt.StrongFocus)
    window.canvas.setFocus()
    window.toolbar = NavigationToolbar2QT(window.canvas, window)
    window.plot_canvas_row = QWidget()
    plot_canvas_row_layout = QHBoxLayout(window.plot_canvas_row)
    plot_canvas_row_layout.setContentsMargins(0, 0, 0, 0)
    plot_canvas_row_layout.addStretch(1)
    plot_canvas_row_layout.addWidget(window.canvas)
    plot_canvas_row_layout.addStretch(1)
    plot_panel.layout().addWidget(window.plot_canvas_row, stretch=1)
    plot_panel.layout().addWidget(window.toolbar)
    right_splitter.addWidget(plot_panel)

    heatmap_panel = QGroupBox("Well Heatmap")
    heatmap_panel.setLayout(QVBoxLayout())
    heatmap_controls = QGridLayout()
    heatmap_panel.layout().addLayout(heatmap_controls)
    heatmap_controls.addWidget(QLabel("Mode"), 0, 0)
    window.heatmap_mode_combo = QComboBox()
    window.heatmap_mode_combo.addItems(["percent", "mfi"])
    window.heatmap_mode_combo.currentIndexChanged.connect(window._schedule_heatmap_update)
    heatmap_controls.addWidget(window.heatmap_mode_combo, 0, 1)
    heatmap_controls.addWidget(QLabel("Metric"), 0, 2)
    window.heatmap_metric_combo = QComboBox()
    window.heatmap_metric_combo.currentIndexChanged.connect(window._schedule_heatmap_update)
    heatmap_controls.addWidget(window.heatmap_metric_combo, 0, 3)
    heatmap_controls.addWidget(QLabel("Channel"), 0, 4)
    window.heatmap_channel_combo = QComboBox()
    window.heatmap_channel_combo.currentIndexChanged.connect(window._schedule_heatmap_update)
    heatmap_controls.addWidget(window.heatmap_channel_combo, 0, 5)
    window.refresh_heatmap_button = compact_button("Refresh", 96)
    window.refresh_heatmap_button.clicked.connect(window._update_heatmap)
    heatmap_controls.addWidget(window.refresh_heatmap_button, 0, 6)
    window.heatmap_status_label = QLabel("Heatmap ready")
    heatmap_controls.addWidget(window.heatmap_status_label, 0, 7)
    window.heatmap_figure = Figure(figsize=(8, 3.8), dpi=100)
    window.heatmap_ax = window.heatmap_figure.add_subplot(111)
    window.heatmap_canvas = FigureCanvasQTAgg(window.heatmap_figure)
    window.heatmap_canvas.setMinimumSize(520, 280)
    window.heatmap_canvas_row = QWidget()
    heatmap_canvas_row_layout = QHBoxLayout(window.heatmap_canvas_row)
    heatmap_canvas_row_layout.setContentsMargins(0, 0, 0, 0)
    heatmap_canvas_row_layout.addStretch(1)
    heatmap_canvas_row_layout.addWidget(window.heatmap_canvas)
    heatmap_canvas_row_layout.addStretch(1)
    heatmap_panel.layout().addWidget(window.heatmap_canvas_row)
    right_splitter.addWidget(heatmap_panel)

    plate_panel = QGroupBox("Plate Layout")
    plate_panel.setLayout(QVBoxLayout())
    plate_panel.layout().addWidget(QLabel("Click a well to select it in the list. Use the sample/exclude controls on the left to edit metadata."))
    plate_button_row = QHBoxLayout()
    plate_button_row.addStretch(1)
    window.plate_editor_panel_button = QPushButton("Open Plate Map Editor")
    window.plate_editor_panel_button.clicked.connect(window.open_plate_map_editor)
    plate_button_row.addWidget(window.plate_editor_panel_button)
    plate_button_row.addStretch(1)
    plate_panel.layout().addLayout(plate_button_row)
    plate_grid = QGridLayout()
    plate_panel.layout().addLayout(plate_grid)
    for col in range(12):
        plate_grid.addWidget(QLabel(str(col + 1)), 0, col + 1)
    for row_idx, row_name in enumerate("ABCDEFGH", start=1):
        plate_grid.addWidget(QLabel(row_name), row_idx, 0)
        for col_idx in range(12):
            well = f"{row_name}{col_idx + 1}"
            button = QPushButton(well)
            button.setMinimumHeight(28)
            button.clicked.connect(lambda _checked=False, w=well: window._select_well_from_plate(w))
            plate_grid.addWidget(button, row_idx, col_idx + 1)
            window.plate_buttons[well] = button
    window.plate_summary_label = QLabel("No wells loaded")
    plate_panel.layout().addWidget(window.plate_summary_label)
    right_splitter.addWidget(plate_panel)
    right_splitter.setSizes([920, 520, 320])

    left_scroll = QScrollArea()
    left_scroll.setWidgetResizable(True)
    left_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
    left_scroll.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
    left_scroll.setWidget(left)

    right_scroll = QScrollArea()
    window.right_scroll = right_scroll
    right_scroll.setWidgetResizable(True)
    right_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
    right_scroll.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
    right_scroll.setWidget(right)

    splitter.addWidget(left_scroll)
    splitter.addWidget(right_scroll)
    splitter.setSizes([640, 960])

    screen = QApplication.primaryScreen()
    if screen is not None:
        geom = screen.availableGeometry()
        left_width = max(420, int(geom.width() * 0.34))
        right_width = max(760, int(geom.width() * 0.56))
        splitter.setSizes([left_width, right_width])
        plot_size = max(520, min(840, int(min(geom.width() * 0.38, geom.height() * 0.58))))
        heat_width = max(520, min(900, int(geom.width() * 0.42)))
        heat_height = max(280, min(460, int(geom.height() * 0.30)))
        window.canvas.setFixedSize(plot_size, plot_size)
        window.heatmap_canvas.setFixedSize(heat_width, heat_height)
        right_splitter.setSizes(
            [
                int(geom.height() * 0.50),
                int(geom.height() * 0.26),
                int(geom.height() * 0.24),
            ]
        )


def placeholder_frame(text):
    from PySide6.QtWidgets import QFrame

    frame = QFrame()
    frame.setFrameShape(QFrame.StyledPanel)
    frame.setMinimumHeight(120)
    layout = QVBoxLayout(frame)
    layout.addWidget(QLabel(text))
    return frame
